import type { ArchiveStats, Creator, SavedVideo } from "./types";

export const mockCreators: Creator[] = [
  {
    id: "mina-makes",
    username: "mina.makes",
    displayName: "Mina",
    initials: "MM",
    accent: "#ff866e",
    videoCount: 24,
    storageLabel: "1.4 GB",
    lastSynced: "2 min ago",
    status: "healthy",
    enabled: true,
  },
  {
    id: "northbound",
    username: "northbound",
    displayName: "Northbound",
    initials: "NB",
    accent: "#75e6d8",
    videoCount: 18,
    storageLabel: "920 MB",
    lastSynced: "8 min ago",
    status: "healthy",
    enabled: true,
  },
  {
    id: "studio-olive",
    username: "studio.olive",
    displayName: "Olive Studio",
    initials: "OS",
    accent: "#c9ff4a",
    videoCount: 13,
    storageLabel: "706 MB",
    lastSynced: "21 min ago",
    status: "syncing",
    enabled: true,
  },
  {
    id: "night-market",
    username: "nightmarket",
    displayName: "Night Market",
    initials: "NM",
    accent: "#a99cff",
    videoCount: 9,
    storageLabel: "488 MB",
    lastSynced: "3 hr ago",
    status: "attention",
    enabled: true,
  },
  {
    id: "slow-sunday",
    username: "slow.sunday",
    displayName: "Slow Sunday",
    initials: "SS",
    accent: "#ffcf66",
    videoCount: 7,
    storageLabel: "312 MB",
    lastSynced: "Yesterday",
    status: "healthy",
    enabled: false,
  },
];

const demoVideo =
  "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4";

export const mockVideos: SavedVideo[] = [
  {
    id: "v-1042",
    creatorId: "mina-makes",
    username: "mina.makes",
    displayName: "Mina",
    title: "Tiny details from today’s studio session",
    description: "Saving the parts I usually forget to photograph.",
    tags: ["process", "studio", "ceramics"],
    mediaType: "video",
    status: "ready",
    videoUrl: demoVideo,
    accent: "#6e402f",
    savedAt: "2026-07-09T17:42:00.000Z",
    savedAtLabel: "12 min ago",
    duration: "0:24",
    sizeLabel: "8.4 MB",
    sourceUrl: "https://www.tiktok.com/",
    likes: 28400,
    bookmarks: 892,
  },
  {
    id: "v-1041",
    creatorId: "northbound",
    username: "northbound",
    displayName: "Northbound",
    title: "First light, no alarm needed",
    description: "The trail was empty and the fog stayed below the ridge.",
    tags: ["outside", "morning", "trail"],
    mediaType: "video",
    status: "ready",
    videoUrl: demoVideo,
    accent: "#19464a",
    savedAt: "2026-07-09T16:18:00.000Z",
    savedAtLabel: "1 hr ago",
    duration: "0:31",
    sizeLabel: "11.2 MB",
    sourceUrl: "https://www.tiktok.com/",
    likes: 13200,
    bookmarks: 514,
  },
  {
    id: "v-1039",
    creatorId: "studio-olive",
    username: "studio.olive",
    displayName: "Olive Studio",
    title: "A color study in six frames",
    description: "Warm light, cold table, one very patient leaf.",
    tags: ["color", "design", "objects"],
    mediaType: "video",
    status: "ready",
    videoUrl: demoVideo,
    accent: "#536326",
    savedAt: "2026-07-09T13:06:00.000Z",
    savedAtLabel: "4 hr ago",
    duration: "0:18",
    sizeLabel: "6.9 MB",
    sourceUrl: "https://www.tiktok.com/",
    likes: 8700,
    bookmarks: 302,
  },
  {
    id: "v-1035",
    creatorId: "night-market",
    username: "nightmarket",
    displayName: "Night Market",
    title: "The last stall still open at midnight",
    description: "Steam, neon, and the best bowl of the week.",
    tags: ["food", "night", "city"],
    mediaType: "video",
    status: "ready",
    videoUrl: demoVideo,
    accent: "#3f245b",
    savedAt: "2026-07-08T23:58:00.000Z",
    savedAtLabel: "Yesterday",
    duration: "0:42",
    sizeLabel: "14.7 MB",
    sourceUrl: "https://www.tiktok.com/",
    likes: 41600,
    bookmarks: 1204,
  },
  {
    id: "v-1031",
    creatorId: "slow-sunday",
    username: "slow.sunday",
    displayName: "Slow Sunday",
    title: "Nothing urgent, just rain on the window",
    description: "A quiet minute for the archive.",
    tags: ["ambient", "rain", "slow"],
    mediaType: "video",
    status: "archived",
    videoUrl: demoVideo,
    accent: "#574c39",
    savedAt: "2026-07-07T18:32:00.000Z",
    savedAtLabel: "2 days ago",
    duration: "0:56",
    sizeLabel: "18.1 MB",
    sourceUrl: "https://www.tiktok.com/",
    likes: 6100,
    bookmarks: 277,
  },
];

export const mockStats: ArchiveStats = {
  creatorCount: 5,
  videoCount: 71,
  storageUsed: "3.8 GB",
  storagePercent: 38,
  newThisWeek: 12,
};
